---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Variables cuantitativas.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Variables categóricas.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Variables categóricas y cuantitativas.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores.
  checked: false
name: Moda
