---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La media, la moda y la mediana coinciden.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La media y la mediana coinciden y son mayores a la moda.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La media y la moda coinciden y son mayores a la mediana.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La media es mayor que la mediana, y ésta es mayor que la moda.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La mediana es mayor que la media, pero menor que la moda.
  checked: true
name: Distribución asimétrica
