---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Se modifica fuertemente
  checked: true
- value: No se modifica
  checked: false
- value: Puede ser negativo
  checked: false
- value: No puede determinarse
  checked: false
name: New exercise
