---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Se modifica fuertemente.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No se modifica.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Puede ser negativo.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No puede determinarse.
  checked: false
name: Desvío estándar
