---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La media
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La moda
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Los cuartiles y la mediana
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El desvío dstandar
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La varianza
  checked: false
name: Ejercicio 5
