---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ignorar el valor faltante.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Completarlo con el promedio de los demás días.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Reemplazarlo con un cero.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores.
  checked: true
name: Ejercicio 2
