---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La mediana no cambia nunca.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La mediana puede cambiar si se modifica el orden de las observaciones.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No hay suficiente información para responder.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores.
  checked: false
name: Mediana
