---
locale: es
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "$146,56"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "$233,33"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "$161,46"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "$135"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "$150,67"
  checked: false
name: Media
