---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Tiene media $2380
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Tiene Desvío 198,72
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Tiene mayor variabilidad relativa que la sucursal de Córdoba
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Tiene menor variabilidad relativa que la sucursal de Córdoba
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambos coeficientes de variación son iguales
  checked: false
name: Ejercicio 4
